import os
# print(dir(os))
# print(os.getcwd())
# os.chdir("C://")
# print(os.getcwd())
# f = open("SaifDiet.txt")
# print(os.listdir())
# print(os.listdir("C://"))
# os.makedirs("This/that")
# os.rename("ZamDiet.txt","AzzamDiet.txt")
# os.rename("AzzamDiet.txt","ZamDiet.txt")
# print(os.path.join("C://","ZamDiet.txt"))
print(os.path.exists("C://Program Files"))
print(os.path.isdir("C://Program Files"))
print(os.environ.get('Path'))